[workspace]
authors = ["wenxu yuan <yuanwenxu123@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "DBiT-spatial-DARLIN"
platforms = ["linux-64"]
version = "0.2.0"

[tasks]
init = { cmd = "pixi install --all --locked && bash install-cli.sh", description = "Install all environments and the dbit command" }

[dependencies]

[feature.dbit.dependencies]
python = "3.12.*"
star = "2.7.10b.*"
fuzzysearch = "0.8.1.*"
pandas = "2.3.3.*"
matplotlib-base = "3.10.*"
umi_tools = "1.1.6.*"
seaborn = "0.13.2.*"
cutadapt = "5.2.*"
scanpy = "1.11.5.*"
python-igraph = ">=1.0.0,<2"
leidenalg = ">=0.11.0,<0.12"
seqtk = ">=1.5,<2"
opencv = ">=4.13.0,<5"
hdf5 = "2.1.*"

[environments]
default = ["dbit"]
