#!/bin/bash
set -o pipefail

show_help() {
    cat << EOF
Usage: $0 <config_file> [fractions]

Downsample all paired mRNA FASTQs into fraction-specific folders, then run the
complete mRNA pipeline once for each fraction.
EOF
}

SCRIPT_DIR=${SATURATION_SCRIPT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)} || exit 1
REPO_DIR=${REPO_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)} || exit 1
QC_SCRIPT_DIR=${QC_SCRIPT_DIR:-$REPO_DIR/script/Quality_Control}

if [[ ${1:-} == -h || ${1:-} == --help ]]; then show_help; exit 0; fi
if [[ $# -lt 1 || $# -gt 2 ]]; then show_help >&2; exit 1; fi

config_file=$1
if [[ ! -f "$config_file" ]]; then
    echo "Error: config file not found: $config_file" >&2
    exit 1
fi
config_abs=$(realpath "$config_file")
# shellcheck source=/dev/null
source "$config_abs"
pixi_env=${pixi_env:-default}
pixi_env_dir=${pixi_env_dir:-$REPO_DIR}

if [[ -z ${mrna_fastq_path:-} ]]; then
    echo "Error: mrna_fastq_path is not set in $config_abs; run 'dbit mrna --input <fastq_dir>' first." >&2
    exit 1
fi

fastq_path=${mrna_fastq_path%/}
fractions=${2:-${saturation_fractions:-0.01,0.02,0.05,0.1,0.2,0.5}}
downsample_seed=${seed:-42}
threads=${mrna_cores:-8}
base_umi_min=${umi_min:-900}
base_gene_min=${gene_min:-300}
output_path="$(dirname "$fastq_path")/saturation"
original_results_path="${mrna_output_path:-$(dirname "$fastq_path")}/results"

if [[ ! -d "$fastq_path" ]]; then
    echo "Error: mRNA FASTQ directory does not exist: $fastq_path" >&2
    exit 1
fi
if [[ ! -f "$QC_SCRIPT_DIR/mrna.sh" ]]; then
    echo "Error: mRNA worker script not found: $QC_SCRIPT_DIR/mrna.sh" >&2
    exit 1
fi
IFS=',' read -ra fraction_array <<< "$fractions"
fraction_labels=()
for fraction in "${fraction_array[@]}"; do
    fraction=$(echo "$fraction" | tr -d '[:space:]')
    fraction_labels+=("$(printf '%.2f' "$fraction")")
done

run_pixi() {
    (
        cd "$pixi_env_dir" || exit 1
        pixi run -e "$pixi_env" "$@"
    )
}

trap 'exit 130' INT
trap 'exit 143' TERM HUP

mkdir -p "$output_path"
echo "=== Starting saturation downsampling ==="

for r1 in "$fastq_path"/*_R1.fq.gz; do
    [[ -e "$r1" ]] || { echo "Error: no *_R1.fq.gz files found in $fastq_path" >&2; exit 1; }
    sample_name=$(basename "$r1" _R1.fq.gz)
    r2="$fastq_path/${sample_name}_R2.fq.gz"
    if [[ ! -f "$r2" ]]; then
        echo "Error: matching R2 file not found for $r1: $r2" >&2
        exit 1
    fi
    log_file="$output_path/${sample_name}_downsample.log"
    {
        echo "Downsample log - $(date)"
        echo "R1: $r1"
        echo "R2: $r2"
        echo "Seed: $downsample_seed"
        echo "Fractions: $fractions"
        echo "---"
    } > "$log_file"

    for fraction in "${fraction_array[@]}"; do
        fraction=$(echo "$fraction" | tr -d '[:space:]')
        fraction_label=$(printf '%.2f' "$fraction")
        fraction_fastq_dir="$output_path/$fraction_label/fastq"
        mkdir -p "$fraction_fastq_dir"

        out_r1="$fraction_fastq_dir/${sample_name}_${fraction_label}_R1.fq.gz"
        out_r2="$fraction_fastq_dir/${sample_name}_${fraction_label}_R2.fq.gz"

        if [[ -f "$out_r1" && -f "$out_r2" ]]; then
            echo "Sample=$sample_name Fraction=$fraction_label already exists, skipping downsampling"
            echo "  Skipped existing: $out_r1" >> "$log_file"
            echo "  Skipped existing: $out_r2" >> "$log_file"
            continue
        fi

        echo "Sample=$sample_name Fraction=$fraction_label"
        seqtk_fraction=$fraction
        if awk -v value="$fraction" 'BEGIN { exit !(value == 1) }'; then
            seqtk_fraction=100%
        fi
        run_pixi seqtk sample -s "$downsample_seed" "$r1" "$seqtk_fraction" | run_pixi pigz -p "$threads" > "$out_r1" || exit 1
        run_pixi seqtk sample -s "$downsample_seed" "$r2" "$seqtk_fraction" | run_pixi pigz -p "$threads" > "$out_r2" || exit 1

        echo "  Output: $out_r1" >> "$log_file"
        echo "  Output: $out_r2" >> "$log_file"
    done
done

echo "=== Running mRNA pipeline for each fraction ==="
for fraction_label in "${fraction_labels[@]}"; do
    fraction_dir="$output_path/$fraction_label"
    fraction_config="$fraction_dir/config.sh"
    if [[ ! -f "$fraction_config" ]]; then
        scaled_umi_min=$(awk -v value="$base_umi_min" -v fraction="$fraction_label" 'BEGIN { printf "%.0f", value * fraction }')
        scaled_gene_min=$(awk -v value="$base_gene_min" -v fraction="$fraction_label" 'BEGIN { printf "%.0f", value * fraction }')
        {
            echo "# Generated by dbit saturation. Edit umi_min and gene_min before rerunning."
            printf 'source %q\n' "$config_abs"
            printf 'mrna_fastq_path=%q\n' "$fraction_dir/fastq"
            printf 'mrna_output_path=%q\n' "$fraction_dir"
            printf 'umi_min=%q\n' "$scaled_umi_min"
            printf 'gene_min=%q\n' "$scaled_gene_min"
        } > "$fraction_config"
        echo "Created fraction config: $fraction_config"
    else
        echo "Reusing fraction config: $fraction_config"
    fi

    echo "Running mRNA pipeline for fraction $fraction_label"
    bash "$QC_SCRIPT_DIR/mrna.sh" "$fraction_config" || {
        echo "Error: mRNA pipeline failed for fraction $fraction_label." >&2
        exit 1
    }
done

echo "=== Plotting saturation curves ==="
run_pixi python "$SCRIPT_DIR/python/plot_saturation.py" \
    --input "$output_path" \
    --original "$original_results_path" \
    --fractions "$fractions" \
    --output "$output_path/saturation_curve.png" || exit 1

echo "Saturation analysis complete: $output_path"
